spring:
  mail:
    host: smtp.yandex.ru
    port: 465
    protocol: smtps
    username: ${EMAIL_USERNAME}
    password: ${EMAIL_PASSWORD}
  liquibase:
    change-log: classpath:db/master.xml
  datasource:
      url: jdbc:postgresql://localhost:5432/events_db
      username: admin
      password: admin
      hikari:
        schema: events_schema
        connection-init-sql: CREATE SCHEMA IF NOT EXISTS events_schema
        connection-timeout: 10000
  jpa:
    generate-ddl: false
    open-in-view: false
